server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#Okta Configuration for API Gateway
okta:
  oauth2:
    issuer: https://dev-78955319.okta.com/oauth2/default
    audience: api://default
    client-id: 0oahg7cwtsgu85Xku5d7
    client-secret: L37K63o-Vf1AfW3TXXQyME-IPJbvExCTA5A-H7n6FiEN5n8dz1-_B94JQZGxoWM2
    scopes: openid, profile, email, offline_access