spring:
  application:
    name: HOTEL-SERVICE
#  config:
#    import: optional:configserver:http://localhost:8085
  cloud:
    config:
      uri: http://localhost:8085
      fail-fast: true
  datasource:
    url: jdbc:mysql://localhost:3306/hotelmicroservices
    username: root
    password: Root@2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9091
#Okta Configuration for API Gateway
okta:
  oauth2:
    issuer: https://dev-78955319.okta.com/oauth2/default
    audience: api://default