spring:
  main:
    allow-circular-references: true
  application:
    name: USER-SERVICE
  cloud:
    config:
      uri: http://localhost:8085
      fail-fast: true
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Root@2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: dev

# Port configuration
server:
  port: 9090

# Actuator configuration
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# Resilience4J configuration
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s

# Security configuration
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: https://dev-78955319.okta.com/oauth2/default
    client:
      registration:
        my-internal-client:
          provider: okta
          authorization-grant-type: client_credentials
          scope: internal
          client-id: 0oahg7cwtsgu85Xku5d7
          client-secret: L37K63o-Vf1AfW3TXXQyME-IPJbvExCTA5A-H7n6FiEN5n8dz1-_B94JQZGxoWM2
      provider:
        okta:
          issuer-uri: https://dev-78955319.okta.com/oauth2/default
# Okta Configuration for API Gateway
okta:
  oauth2:
    issuer: https://dev-78955319.okta.com/oauth2/default
    audience: api://default
