server:
  port: 9092
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: RATING-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/Ratingmicroservices
      database: Ratingmicroservices

  # Explicitly disable datasource auto-configuration
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core: DEBUG
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    build:
      enabled: true

#Okta Configuration for API Gateway
okta:
  oauth2:
    issuer: https://dev-78955319.okta.com/oauth2/default
    audience: api://default